{
 "title": "FastApp Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "/predict", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Prediction Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/predict\", status=\"2xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Prediction Failure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/predict\", status!=\"2xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/predict\"}[1m])/rate(http_request_duration_seconds_count{handler=\"/predict\"}[1m])*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "/square", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Prediction Failure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/square\", status!=\"2xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/square\"}[1m])/rate(http_request_duration_seconds_count{handler=\"/square\"}[1m])*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/square\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Prediction Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/square\", status=\"2xx\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}