global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapp.example.com:8000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor.example.com:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['nexporter.example.com:9100']